apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-fpm-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-fpm
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50